PaginaProyecto/PaginaProyecto/Controllers/EventoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;
using System.Net.Mail;
using PaginaProyecto.Models;
using System.IO;

namespace PaginaProyecto.Controllers
{
    public class EventoController : Controller
    {
        public ActionResult MisEventos()
        {
            ViewBag.NoHayEventos = false;
            Evento oEvento = new Evento();
            Usuario oUsuario = (Usuario)Session["UsuarioLogueado"];
            List<Evento> listaEventos = oEvento.ListarEventosUsuario(oUsuario.UsuarioID);
            if (listaEventos.Count > 0)
            {
                ViewBag.listaEventosUsuario = listaEventos;
            }
            else
            {
                ViewBag.NoHayEventos = true;
            }
            ViewBag.Usuario = oUsuario;
            return View();
        }
        // GET: Evento
        public ActionResult AgregarEvento()
        {
            ViewBag.Usuario = (Usuario)Session["UsuarioLogueado"];
            return View();
        }

        // POST : Evento/AgregarEvento/
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AgregarEvento(Evento oEvento)
        {
            Usuario oUsuario = (Usuario)Session["UsuarioLogueado"];
            ViewBag.Usuario = oUsuario;
            bool nombreInvalido = oEvento.ExisteEvento();
            if (ModelState.IsValid && nombreInvalido == false)
            {
                if (oEvento.Imagen != null && oEvento.Imagen.ContentLength > 0)
                {
                    var filename = Path.GetFileName(oEvento.Imagen.FileName);
                    var path = Path.Combine(Server.MapPath("~/Content/Eventos"), filename);
                    oEvento.Imagen.SaveAs(path);
                    oEvento.ImagenString = oEvento.Imagen.FileName;
                    oEvento.UsuarioID = oUsuario.UsuarioID;
                    oEvento.InsertarEvento();
                }
                else
                {
                    oEvento.ImagenString = "default.gif";
                    oEvento.UsuarioID = oUsuario.UsuarioID;
                    oEvento.InsertarEvento();
                }
                TempData["EventoCreado"] = oEvento;
                return RedirectToAction("UnEvento", new { idEvento = -1});
            }
            else
            {
                if (nombreInvalido)
                {
                    ViewBag.NombreUsado = "El nombre del evento ya fue usado";
                }
                return View();
            }
        }
        // GET : /Evento/HomeUsuario
        public ActionResult HomeEventos()
        {
            ViewBag.NoHayEventos = false;
            Evento oEvento = new Evento();
            List<Evento> listaEventos = oEvento.ListarEventos();
            if (listaEventos.Count > 0)
            {
                ViewBag.ListaEventos = listaEventos;
            }
            else
            {
                ViewBag.NoHayEventos = true;
            }
            Usuario oUsuario = (Usuario)Session["UsuarioLogueado"];
            ViewBag.Usuario = oUsuario;
            return View();
        }

        public ActionResult UnEvento(int idEvento) {
            Evento oEvento = new Evento();
            if (idEvento != -1)
            {
                oEvento.EventoID = idEvento;
                oEvento.TraerEvento();
            }
            else
            {
                oEvento = (Evento)TempData["EventoCreado"];
            }
            Usuario oUsuario = (Usuario)Session["UsuarioLogueado"];
            oEvento.recaudadoEvento();
            oEvento.CantidadDeDonantesEvento();
            oEvento.UsuarioAdmin.TraerUsuario();
            double porcen = 0;
            porcen = ((double)oEvento.Recaudado / (double)oEvento.Meta) * 100;
            int intporcen = Convert.ToInt32(Math.Floor(porcen));
            ViewBag.Porcentaje = intporcen;
            ViewBag.Usuario = oUsuario;
            ViewBag.unEvento = oEvento;
            return View();
        }

        public ActionResult ModificarEvento(int idEvento)
        {
            Evento oEvento = new Evento();
            oEvento.EventoID = idEvento;
            oEvento.TraerEvento();

            ViewBag.unEvento = oEvento;
            Usuario oUsuario = (Usuario)Session["UsuarioLogueado"];
            ViewBag.Usuario = oUsuario;
            return View();
        }

        // POST : Evento/ModificarEvento/
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ModificarEvento(Evento oEvento, int id)
        {
            oEvento.EventoID = id;
            if (oEvento.Imagen != null && oEvento.Imagen.ContentLength > 0)
            {
                var filename = Path.GetFileName(oEvento.Imagen.FileName);
                var path = Path.Combine(Server.MapPath("~/Content/Eventos"), filename);
                oEvento.Imagen.SaveAs(path);
                oEvento.ImagenString = oEvento.Imagen.FileName;  
            }
            else
            {
                oEvento.ImagenString = "default.gif";
            }
            oEvento.ModificarEvento();
            return RedirectToAction("MisEventos");
        }

        public ActionResult Donar(int idEvento)
        {
            ViewBag.EventoID = idEvento;
            Usuario ousuario = (Usuario)Session["Usuariologueado"];
            ViewBag.Usuario = ousuario;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Donar(Donacion oDonacion, int idEvento)
        {
            if (ModelState.IsValid)
            {
                Evento oevento = new Evento();
                oevento.EventoID = idEvento;
                oevento.TraerEvento();
                oevento.recaudadoEvento();   
                Usuario oUsuario = (Usuario)Session["UsuarioLogueado"];
                int idUsuario = oUsuario.UsuarioID;
                if (oevento.Recaudado + oDonacion.Monto >= oevento.Meta)
                {
                    oevento.UsuarioAdmin.TraerUsuario();
                    MandarMail(oevento);
                }
                oDonacion.donar(idEvento, idUsuario);
                MandarMail1(oUsuario, oDonacion);
                return RedirectToAction("UnEvento", new { idEvento = idEvento});
            }
            else
            {
                Usuario ousuario = (Usuario)Session["Usuariologueado"];
                ViewBag.Usuario = ousuario;
                return View();
            }
        }
        public void MandarMail1 (Usuario oUsuario, Donacion oDonacion)
        {
            MailMessage mailMessage = new MailMessage();
            mailMessage.To.Add("uripaluch2@gmail.com");
            mailMessage.To.Add(oUsuario.Email);
            mailMessage.From = new MailAddress("proyectodonaciones@gmail.com");
            mailMessage.Subject = "Donacion aceptada";
            mailMessage.Body = "Aceptamos tu donacion de $"+oDonacion.Monto+" Muchas gracias por contribuir.";
            SmtpClient smtpClient = new SmtpClient("smtp.gmail.com");
            smtpClient.EnableSsl = true;
            smtpClient.DeliveryMethod = SmtpDeliveryMethod.Network;
            smtpClient.Credentials = new NetworkCredential("proyectodonaciones@gmail.com", "proyecto123");
            smtpClient.Port = 25;
            smtpClient.Send(mailMessage);
        }

        public void MandarMail(Evento oEvento)
        {
            MailMessage mailMessage = new MailMessage();
            mailMessage.To.Add(oEvento.UsuarioAdmin.Email);
            mailMessage.From = new MailAddress("proyectodonaciones@gmail.com");
            mailMessage.Subject = "Donacion aceptada";
            mailMessage.Body = "Se completo la meta de $" + oEvento.Meta;
            SmtpClient smtpClient = new SmtpClient("smtp.gmail.com");
            smtpClient.EnableSsl = true;
            smtpClient.DeliveryMethod = SmtpDeliveryMethod.Network;
            smtpClient.Credentials = new NetworkCredential("proyectodonaciones@gmail.com", "proyecto123");
            smtpClient.Port = 25;
            smtpClient.Send(mailMessage);
        }
    }
}

PaginaProyecto/PaginaProyecto/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <link rel="stylesheet" type="text/css" href=@Url.Content("agency.css") >

    <link href="vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>


</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nombre de aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

PaginaProyecto/PaginaProyecto/Views/Shared/_MiLayout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/MiEstilo/css/")agency.css" >

    <link href="@Url.Content("~/Content/")bootstrap.min.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="@Url.Content("~/Content/MiEstilo/font-awesome/css/")font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>

    <!-- Theme CSS -->
    <link href="@Url.Content("~/Content/MiEstilo/css/")agency.min.css" rel="stylesheet">
    <link href="@Url.Content("~/Content/MiEstilo/css/")login.css" rel="stylesheet">

</head>
<body>
    <nav id="mainNav" class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container">
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span><i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="@Url.Action("Index", "Home")">The ether project</a>
            </div>

            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <li>
                        <a class="page-scroll" href="@Url.Action("HomeEventos", "Evento")">EVENTOS</a>
                    </li>
                    <li>
                        <div class="dropdown">
                            <img src="@Url.Content("~/Content/MiEstilo/img/logos/")Iconousuario.png" class="btn dropdown-toggle" type="button" data-toggle="dropdown" style="margin-top: 0px">
                            <ul class="dropdown-menu" style="background-color: #fec503;">
                              <li><a href="@Url.Action("RegistrarUsuario", "RegistracionUsuario")">Registrarse</a></li>
                              <!-- Large modal -->
                              <li><a href="@Url.Action("LoguearUsuario", "RegistracionUsuario")" >Iniciar Sesion</a></li>
                            </ul>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <!-- jQuery -->
    <script src="@Url.Content("~/Content/MiEstilo/js/")jquery.min.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="@Url.Content("~/Content/MiEstilo/js/")bootstrap.min.js"></script>
    <!-- Plugin JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js" integrity="sha384-mE6eXfrb8jxl0rzJDBRanYqgBxtJ6Unn4/1F7q4xRRyIw7Vdg9jP4ycT7x1iVsgb" crossorigin="anonymous"></script>
    <!-- Contact Form JavaScript -->
    <script src="@Url.Content("~/Content/MiEstilo/js/")jqBootstrapValidation.js"></script>
    <!-- Theme JavaScript -->
    <script src="@Url.Content("~/Content/MiEstilo/js/")agency.min.js"></script>

    <div>
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>

PaginaProyecto/PaginaProyecto/Views/Shared/_MiLayoutLogueado.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/MiEstilo/css/")agency.css">

    <link href="@Url.Content("~/Content/")bootstrap.min.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="@Url.Content("~/Content/MiEstilo/font-awesome/css/")font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>

    <!-- Theme CSS -->
    <link href="@Url.Content("~/Content/MiEstilo/css/")agency.min.css" rel="stylesheet">
    <link href="@Url.Content("~/Content/MiEstilo/css/")login.css" rel="stylesheet">

</head>
<body>
    <nav id="mainNav" class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container">
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span><i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="#">The ether project</a>
            </div>

            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <li>
                        <a class="page-scroll" href="@Url.Action("HomeEventos", "Evento")">EVENTOS</a>
                    </li>
                    <li>
                        <div class="dropdown">
                            <img src="@Url.Content("~/Content/Usuarios/")@ViewBag.Usuario.ImagenString" class="btn dropdown-toggle img-circle" type="button" data-toggle="dropdown" style="margin-top: 0px; width:70px; border-radius:100px">
                            <ul class="dropdown-menu" style="background-color: #fec503;">
                                <li><a href="@Url.Action("MiPerfil", "RegistracionUsuario")">Mi Perfil</a></li>
                                <li><a href="@Url.Action("MisEventos", "Evento")">Mis Eventos</a></li>
                                <li><a href="@Url.Action("Desloguear", "RegistracionUsuario")">Cerrar Sesion</a></li>
                            </ul>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <!-- jQuery -->
    <script src="@Url.Content("~/Content/MiEstilo/js/")jquery.min.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="@Url.Content("~/Content/MiEstilo/js/")bootstrap.min.js"></script>
    <!-- Plugin JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js" integrity="sha384-mE6eXfrb8jxl0rzJDBRanYqgBxtJ6Unn4/1F7q4xRRyIw7Vdg9jP4ycT7x1iVsgb" crossorigin="anonymous"></script>
    <!-- Contact Form JavaScript -->
    <script src="@Url.Content("~/Content/MiEstilo/js/")jqBootstrapValidation.js"></script>
    <!-- Theme JavaScript -->
    <script src="@Url.Content("~/Content/MiEstilo/js/")agency.min.js"></script>

    <div>
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>